// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Models;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(SubaContext))]
    [Migration("20220824091145_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebAPI.Models.ContactInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("OpeningHoursWeekdays")
                        .HasColumnType("longtext");

                    b.Property<string>("OpeningHoursWeekends")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("ContactInfo");
                });

            modelBuilder.Entity("WebAPI.Models.Gallery", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Gallery_Date")
                        .HasColumnType("longtext");

                    b.Property<string>("Gallery_Post")
                        .HasColumnType("longtext");

                    b.Property<string>("Gallery_TxT")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Gallery");
                });

            modelBuilder.Entity("WebAPI.Models.InputInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Diving")
                        .HasColumnType("longtext");

                    b.Property<string>("DivingCourses")
                        .HasColumnType("longtext");

                    b.Property<string>("DivingEquimentDesc")
                        .HasColumnType("longtext");

                    b.Property<string>("DivingEquipment")
                        .HasColumnType("longtext");

                    b.Property<string>("ServicingOfDivingEquipment")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("InputInfo");
                });

            modelBuilder.Entity("WebAPI.Models.Login", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("WebAPI.Models.Products", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Available")
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Price")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebAPI.Models.TourInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .HasColumnType("longtext");

                    b.Property<string>("DrivingType")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("NumOfSpotsLeft")
                        .HasColumnType("int");

                    b.Property<string>("PayWith")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PricePerPerson")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SpotDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("TourInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
