// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScubaAPI.Models;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(StedContext))]
    partial class StedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ScubaAPI.Models.IMG", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cover")
                        .HasColumnType("longtext");

                    b.Property<string>("Default")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<int>("StedID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ScubaAPI.Models.Kontakt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<string>("Mail")
                        .HasColumnType("longtext");

                    b.Property<string>("Navn")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kontakt");
                });

            modelBuilder.Entity("ScubaAPI.Models.Sted", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<string>("Dybde")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Lon")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Navn")
                        .HasColumnType("longtext");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Steder");
                });

            modelBuilder.Entity("ScubaAPI.Models.Tilmeld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Hojde")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .HasColumnType("longtext");

                    b.Property<string>("Navn")
                        .HasColumnType("longtext");

                    b.Property<string>("Tlfnr")
                        .HasColumnType("longtext");

                    b.Property<int>("TurID")
                        .HasColumnType("int");

                    b.Property<int>("Vaegt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Signup");
                });

            modelBuilder.Entity("ScubaAPI.Models.Tur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("longtext");

                    b.Property<string>("Dato")
                        .HasColumnType("longtext");

                    b.Property<string>("Navn")
                        .HasColumnType("longtext");

                    b.Property<int>("Pladser")
                        .HasColumnType("int");

                    b.Property<int>("Pris")
                        .HasColumnType("int");

                    b.Property<int>("Rabat")
                        .HasColumnType("int");

                    b.Property<int>("StedID")
                        .HasColumnType("int");

                    b.Property<string>("Tid")
                        .HasColumnType("longtext");

                    b.Property<int>("Tilmeldte")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Turer");
                });

            modelBuilder.Entity("ScubaAPI.Models.Type", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DykType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
